# Generated by Django 2.1 on 2017-10-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplom',
            name='songoson',
            field=models.BooleanField(default=False),
        ),
    ]
